### PR TITLE
Fix/46

### LINKED ISSUE #46: Catch the exception and show file not found/loaded error
Screen Shot 2021-10-13 at 1 37 30 PM

### PR DESCRIPTION
**Pull request by aidan-starke**
Closes #46

### CODE REVIEW

File: components/nft/NFTDataWrapper.tsx [hunk 1]
```diff
@@ -62,7 +62,8 @@ const NFTDataWrapper: React.FC<{
           .get(metadataUrl)
           .then(function (response) {
             const { data } = response;
-            if (data) {
+            if (!data.image) setError("Image not found");
+            else if (data) {
               const metadata = {
```
Comment (ken-centrality) [inline components/nft/NFTDataWrapper.tsx:67]: you can use optional chaining here to make sure `data` exists also, plus return early after `setError` to avoid having `else if`.

e.g

```
if(!data?.image) return setError("Image not found");
```

**Review by ken-centrality — CHANGES_REQUESTED** [review]
Just a small recommendation using my new favourite thing in JS, optional chaining!

I do think we need support the new metadata format from `glorious-nft` but let's put it in a separate issue

File: components/nft/NFTDataWrapper.tsx (hunk 1 above)
Comment (aidan-starke) [reply components/nft/NFTDataWrapper.tsx:67]: does this mean we can remove `if (data)` completely?

Comment (ken-centrality) [reply components/nft/NFTDataWrapper.tsx:67]: yes that's correct, super neat and tidy

**Review by ken-centrality — APPROVED** [review]
